services:
  - type: web
    name: stembridge-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: stembridge-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: stembridge-db
    databaseName: stemcelldb
    user: stemcell_user
    plan: free
