# Generated by Django 6.1 on 2026-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('report_type', models.CharField(default='GENERAL', max_length=50)),
                ('status', models.CharField(default='Analyzed', max_length=50)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_reports',
                'ordering': ['-id'],
            },
        ),
    ]
