# Generated by Django 6.1 on 2026-09-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=10)),
                ('record_id', models.BigIntegerField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(db_column='item_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-item_id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-patient_id'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_id', models.AutoField(db_column='research_id', primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('lead_scientist', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research',
                'ordering': ['-research_id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(db_column='staff_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['-staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(db_column='donor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='stemcell_core.patient')),
            ],
            options={
                'db_table': 'donors',
                'ordering': ['-donor_id'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(db_column='storage_id', primary_key=True, serialize=False)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('units', models.IntegerField(default=1)),
                ('donor', models.ForeignKey(blank=True, db_column='donor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_records', to='stemcell_core.donor')),
            ],
            options={
                'db_table': 'storage',
                'ordering': ['-storage_id'],
            },
        ),
    ]
