# Generated by Django 6.1 on 2026-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemcell_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_id']},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contact',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
