# Generated by Django 6.1 on 2026-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stemcell_core', '0002_alter_staff_options_remove_staff_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemCellBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stem_cell_banks',
                'ordering': ['id'],
            },
        ),
    ]
